### PR TITLE
Add basic OAuth implementation

### PR DESCRIPTION
**Pull request by FranciscoDA**
This adds some basic support for OAuth authorization (#2)
Also fixes a strange bug where retweeters' ids weren't being stringified

Btw: I accidentally messed up the indentation so I reindented the whole file, sorry :/

### CODE REVIEW

**Comment by Rumpelcita** [comment]
Hi, why did you close this? Was it because of the indentation?

**Comment by FranciscoDA** [comment]
@Rumpelcita Sorry, I thought it wouldn't get merged. I've just reopened it :+1:

**Review by Rumpelcita — APPROVED** [review]

**Comment by Rumpelcita** [comment]
Hey, I merged this, but when I tested it on glitch, I get the following error: 

{"statusCode":401,"data":"{\"errors\":[{\"code\":32,\"message\":\"Could not authenticate you.\"}]}"}

So I'm reverting the changes.

**Comment by FranciscoDA** [comment]
That's odd. Maybe it's something in the app's configuration in Twitter's developer panel? It makes sense that Twitter will refuse to give a request token if the consumer key, consumer secret or callback url are incorrect, but wouldn't an HTTP 403 status be more appropiate?

Here's my current config:
my app config

**Comment by Rumpelcita** [comment]
Okay, it seems the issue was that server.js wasn't using glitch's credentials. I fixed it, so now everything is working as it should and I added the reporting option.

**Pull request merged**
